### ISSUE TITLE
Add lazy evaluation for assertion messages

### ISSUE THREAD

**Issue by ruckc** [junit-team/junit4#1133] opened 2015-04-29 15:57 UTC
It would be nice if `assertEquals(String message, Object expected, Object actual)` was overloaded with a lazy evaluated String.format style Message object.

Example:
   `assertEquals(Message message, Object expected, Object actual)`
Usage:
   `assertEquals(message("This is bad %s %s", expected, actual), expected, actual)`

the message() could be added to Assert for inclusion in the static includes, and it could return a lazy eval Message object.  This would enable faster unit tests while minimizing complexity in unit tests.  Reference https://twitter.com/NathanTippy/status/593435755453677568

**Comment by nathantippy** [comment] 2015-04-29 16:05
Also take a peak at how SLF4j does this for faster logging when the log level may not go that deep.

**Comment by kcooney** [comment] 2015-04-29 16:20
•assertEquals()` already includes the expected and actual values in the exceptuon message. Would you not want it to do that if you passed in whatever value is returned from `message()`? Could you pass other optional.values?

BTW, I am.not currently concerned about performance here. Assertion failures should be rare and fixed right away, and the methods throw exceptions on failure. Logging framework gave different performance needs.

**Comment by nathantippy** [comment] 2015-04-29 16:28
The situation happens when there are cases that the expected and actual values are not enough information to debug the failure.  I want to see more system state to help me find the problem.  Gathering this information takes time and should only be done upon failure.  I have a work around using a finally block however it is less than elegant.

When I have a large % of coverage in projects it takes a long time get a good build due to the time it takes the test to run. If every assertEquals is doing extra object creation that will never be used then I see a growing impact of this wasted work with each test I add.  

For very large projects performance of the passing case becomes very important.

**Comment by ruckc** [comment] 2015-04-29 16:43
I've submitted a potential Pull request for this in #1134

**Comment by kcooney** [comment] 2015-04-29 17:51
Can you give a specific example where the expected and actual values are not enough to debug a failure and this proposed API would help (including a code snippet of how you would use this API to solve the problem)? Thanks!

**Comment by nathantippy** [comment] 2015-04-30 13:03
I would like to redirect the conversation and continue with #1134

**Comment by kcooney** [comment] 2015-04-30 14:23
@nathantippy could you please answer my previous question? The pull is addressing a specific solution to a problem. I'd like to make sure we're all on the same page about what the problem is, and discuss what APIs would be best for solving that problem.

**Comment by nathantippy** [comment] 2015-04-30 15:19
There are times when there is a matching failure between expected and
actual however those two numbers are not enough for diagnosis.
I would like to present to the developer the last 10 successful values in
the stream.
This gives valuable context for the failure to help the developer determine
where the fault happened.


To speed up Java builds without building up this complex message every
time.  I find my self following this pattern

boolean ok=false;
try{
//JUnit ASSERTS W/ FIXED MSGS
ok=true; }
finally {
if (!ok) { //VERBOSE MSGS HERE }
}

But this above code is a work around and not  something most people should
do.

Instead something like the following which lets me check the positions of
the streams and the values at those positions.
Note that the reporter (which is my class, not part of JUnit) is only
created once and would return a CharSequence displaying
a different trailing 10 fields depending on the active state of stream.

CharSequence message = new StreamTailReporter(stream, 10);

assertEquals(message, expectedPosA, reportedPosB);
assertEquals(message, expectedValueA, reportedValueB);

I am happy to answer any other questions you might have.   Thanks for
looking at this.








On Thu, Apr 30, 2015 at 9:24 AM, Kevin Cooney <notifications@github.com>
wrote:

> @nathantippy <https://github.com/nathantippy> could you please answer my
> previous question? The pull is addressing a specific solution to a problem.
> I'd like to make sure we're all on the same page about what the problem is,
> and discuss what APIs would be best for solving that problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junit-team/junit/issues/1133#issuecomment-97816366>.
>



-- 
Nathan Tippy
Principal Software Engineer

Blog : http://nathan.tippy.name
Phone: 636-295-5785
Email: nathan@tippy.name

**Comment by kcooney** [comment] 2015-04-30 16:34
Thanks for the detailed response. It helps.

Your example doesn't use the `Message` class that you are introducing in your pull. If we took that class out of your pull, would that be a problem?

I can think of one solution that requires no changes to JUnit. You could create a `StreamTailChecker` class that has higher-level assertion methods, and it can have a field of type `StreamTailReporter`. If any of the assertion methods fail, you can construct a useful message that includes the message from the `StreamTailReporter` plus additional details.

    StreamTailChecker checker = new StreamTailChecker(stream, 10);
    checker.assertHasValue(expectedValue);

...


    public void assertHasValue(Value expectedValue) {
      if (!getValue().equals(expectedValue)) {
         failNotEquals(reporter.toString(), expectedValue, getValue();
      }
    }

This requires a bit more code, but if you have multiple test methods doing assertions, your code becomes more readable. As an added benefit, the stack traces for failures are more informative because of the naming of your higher-level assertion methods.

**Comment by nathantippy** [comment] 2015-04-30 23:33
I would be very happy without the Message.  I think the CharSequence is the most important part, how people use it is up to them.

Your example is nice but I am not sure most developers would go to those lengths.  They would also expect the equals part to be done by JUnit rather than themselves.  failNotEquals like assertEquals takes a String so all we did here is just put a guard around it.  I think this makes it harder to read.

So I am still in favor of the CharSequence change, but I am happy to narrow the scope to only that change.

**Comment by kcooney** [comment] 2015-04-30 23:41
@nathantippy just giving you options. Even if we merged your change this week, it would be 6-18 months before you would see it in a public release.

I do realize my solution does require more code, but remembering to pass a specific `CharSequence` variable to all your assertion calls is error-prone. Creating a mini-DSL for testing is often well worth the time spent writing it.

**Comment by marcphilipp** [comment] 2015-05-01 16:23
I'm pretty sure `CharSequence` is not very popular or widely known. I fear that if we changed the signature from `String` to `CharSequence` we would surprise a lot of people.

In Java 8 one would probably rather use `Supplier<String>` to achieve lazy evaluation. We could add assertion methods that use a supplier to JUnit Lambda (which is currently on hold).

**Comment by kcooney** [comment] 2015-05-01 16:42
I was going to make a similar comment. Using `CharSequence` as a lazy-evaluated string is a bit clunky. Also, the `message()` methods would have to keep a reference to the argument array, and arrays are mutable, which is a bit problematic. Looking at how Lambdas can be used to allow just-in-time evaluation of assertion messages is probably the way to go.

**Comment by nathantippy** [comment] 2015-05-01 17:59
Going forward that is the way to go with Java 8 however using CharSequence
would be the cleanest approach for Java 7 and legacy projects that may have
problems with their build time.  I am not sure we will see lambdas any time
soon for android development.

On Fri, May 1, 2015 at 11:42 AM, Kevin Cooney <notifications@github.com>
wrote:

> I was going to make a similar comment. Using CharSequence as a
> lazy-evaluated string is a bit clunky. Also, the message() methods would
> have to keep a reference to the argument array, and arrays are mutable,
> which is a bit problematic. Looking at how Lambdas can be used to allow
> just-in-time evaluation of assertion messages is probably the way to go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junit-team/junit/issues/1133#issuecomment-98174867>.
>



-- 
Nathan Tippy
Principal Software Engineer

Blog : http://nathan.tippy.name
Phone: 636-295-5785
Email: nathan@tippy.name

**Comment by kcooney** [comment] 2015-05-01 19:21
Have you considered asking for something like this in a DSL-based assertion framework like Truth? The syntax would be cleaner:

    assert_()
       .withFailureMessage("context ℅s", context)
       .that(myBooleanResult)
      .named("hasError()").isTrue()

**Comment by kcooney** [comment] 2015-05-01 19:27
Also, keep in mind that an API that works with Lambdas could also be called from coded that was compiled with Java 5. In your case, `StreamTailReporter` would implement an interface that had one method (perhaps ` String getMessage()`).

**Comment by kcooney** [comment] 2015-05-01 23:44
I updated the summary to not imply a specific solution.

**Comment by ashleyfrieze** [comment] 2015-05-04 22:45
As I mentioned in #1134 the proposal doesn't avoid the evaluation of the values that would be inserted into the string. Lambdas seem like the answer.

**Comment by ashleyfrieze** [comment] 2015-05-13 09:20
See https://github.com/hamcrest/JavaHamcrest/pull/102 as a potential solution to this.

**Comment by marcphilipp** [comment] 2015-11-23 14:47
Our new prototype codenamed JUnit Lambda brings support for lazily evaluated assertion messages.

Please take a look:
https://github.com/junit-team/junit-lambda/wiki/Prototype-Writing-Test-Cases#assertions

**Comment by marcphilipp** [comment] 2016-05-02 11:46
I'm closing this issue because JUnit 5 supports lazy evaluated assertion messages:
http://junit.org/junit5/docs/current/user-guide/#assertions

**Closed by marcphilipp** 2016-05-02 11:46 UTC
