### ISSUE TITLE
ErrorCollector will not fail tests if used in conjunction with an ExpectedException

### ISSUE THREAD

**Issue by alexblanck** [junit-team/junit4#1466] opened 2017-06-14 23:31 UTC
I stumbled across a bit of an obscure edge case in one of our tests using Junit 4.12 and I'm wondering if this is a bug or if it's expected behavior.

It appears that any errors collected by the `ErrorCollector` are not reported if test throws an exception and the exception is also expected by the `ExpectedException`

For an example, see the first test method here:

```java
package com.alexblanck;

import static org.hamcrest.CoreMatchers.equalTo;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ErrorCollector;
import org.junit.rules.ExpectedException;

public class ConflictingRules {

    @Rule
    public ErrorCollector errors = new ErrorCollector();

    @Rule
    public ExpectedException exception = ExpectedException.none();

    @Test
    public void succeeds_butExpectedToFailBasedOnErrorCollector() {
        errors.checkThat(3, equalTo(4));
        exception.expect(IllegalStateException.class);
        throw new IllegalStateException();
    }

    @Test(expected = IllegalStateException.class)
    public void fails_basedOnAnnotation_asExpected() {
        errors.checkThat(3, equalTo(4));
        throw new IllegalStateException();
    }

    @Test
    public void fails_basedOnErrorCollector_asExpected() {
        errors.checkThat(3, equalTo(4));
    }

    @Test
    public void succeeds_basedOnExpectedException_asExpected() {
        exception.expect(IllegalStateException.class);
        throw new IllegalStateException();
    }
}
```

As you can see in the example, the test does fail as expected when `@Test(expected=` annotation instead of the `ExpectedException` rule.

Digging into the code a bit, it seems that the problem is an ordering issue. `ErrorCollector` extends`Verifier` and therefore only checks for the presence of errors after the base statement evaluates without an exception. If the `expected` annotation is used, the "base" statement is a `ExpectException` statement, so it does not throw and the `ErrorCollector` runs.

Using a RuleChain, I can get my example to behave as expected by forcing the ErrorCollector to be the "outerRule":

```
@Rule
public RuleChain chain = RuleChain.outerRule(errors).around(exception);
```

I'm not sure if this causes other unintended behavior though. I found [another issue](https://github.com/junit-team/junit4/issues/1012) that talks about a similar ordering issue, but it proposed the reverse ordering.

**Comment by panchenko** [comment] 2017-06-14 23:57
I think this is a duplicate of #1436

**Comment by kcooney** [comment] 2017-06-15 00:16
Agreed that this is a duplicate. Short term, use `RuleChain` to order the rules. In JUnit 4.13 you will have two more choices: 1. use the `order` attribute of `Rule` (see #1445) and 2. use `Assert.assertThrows` or  `Assert.expectThrows`  instead of `ExpectedException`

Is there anything we could have done so you could have resolved the issue on your own? If we deprecated  `ExpectedException` in favor of Assert.assertThrows` or  `Assert.expectThrows`  would that have helped?

**Comment by alexblanck** [comment] 2017-06-15 16:28
Thanks for pointing me to the duplicate issue. I didn't make the initially connection between the two, but now I see that they are related.

I want to echo what @Gaibhne says in the other issue: I now understand why this is happening but I would have never known beforehand to pay attention to the ordering of `ExpectedException` with respect to other rules. This type of problem is particularly nasty because it causes false positives which are difficult to discover unless you know a test should be failing.

Deprecating ExpectedException with a mention that it doesn't work as expected when combined with other `Verifier`-based Rules (like `ErrorCollector`) would be one option. In our code (still on Junit 4.12), I think I'm going to end up substituting the `ExpectedException` rules with a method we wrote that is very similar to Assert.assertThrows.

Another option might be to automatically place `ExpectedException` rules as the "innermost" rule. I understand that this probably isn't practical given that this option will not work with custom rules that also recover from thrown exceptions. Figuring out how this works with custom orderings could also be problematic.

**Comment by kcooney** [comment] 2017-06-16 00:33
I don't see how we can automatically reorder rules without breaking existing tests. How do we know the test isn't expecting `ExpectedException` to catch exceptions thrown by `Verifier`?

I think deprecating `ExpectedException` would be the best path forward.

That being said, the problem isn't unique to `ExpectedException`. Any rule could throw an exception, and it's unclear whether the developer wants the `Verifier` rule to executed before or after any given rule.

It's possible that after 4.13 is released, someone could write an Error Prone check that warnings about test classes that have multiple `@Rule` or `@TestRule` annotations that don't have an `order` attribute.

**Closed** 2018-05-02 07:25 UTC
