### ISSUE TITLE
Unrooted Tests when running single test in Eclipse with failing @AfterClass

### ISSUE THREAD

**Issue by htetmyomyint** [junit-team/junit4#1370] opened 2016-10-12 03:36 UTC
I used JUnit 4 to test method that works with Apache Storm and Elasticsearch. 
When tested method throws an exception Unrooted Tests appears at JUnit console of Eclipse.
When tested method works correctly, JUnit is correct.

**Comment by kcooney** [comment] 2016-10-12 04:15
Could you give some steps to reproduce, including a sample failed test? Does it require Apache Storm and Elasticsearch to reproduce?

**Comment by htetmyomyint** [comment] 2016-10-12 05:39
@kcooney , Unrooted Tests still happen without Apache Storm and Elasticsearch.
It happens with sample code like following.

//Target class
package mypackage;

public class MyClass
{
    public Object throwExcep() throws Exception
    {
        throw new Exception();
     //  return null;
    }
}

and JUnit method ,
    @Test//(expected = Exception.class)
    public void test_5tth_notexistedcluster() throws Exception
    {
      MyClass myClass= new MyClass();
      myClass.throwExcep();
    }
I added my environment information.
Project type : Maven project
Eclipse : Mars.1 Release (4.5.1)
Platform : Windows 10

**Comment by kcooney** [comment] 2016-10-12 06:43
@htetmyomyint I formatted your code. Does it look right? Does the test class have a base class? Does it use a custom runner?

Can you provide a screenshot? Does it happen with other versions of Eclipse? I ask because this is a very simple test, so it shouldn't give you weird output.

**Comment by kcooney** [comment] 2016-10-12 06:46
also, these might help:

- http://stackoverflow.com/questions/120889/unrooted-tests
- http://stackoverflow.com/questions/23229538/junit-test-unrooted-tests-initializationerror
- http://forum.spring.io/forum/spring-projects/data/60152-unrooted-tests-eclipse-and-running-individual-junit-4-tests

**Comment by htetmyomyint** [comment] 2016-10-12 07:45
@kcooney , Thanks for answers. 

Actually code inside @AfterClass has the problem.
But I can't see all error stacktrace and wrongly located the error.

Regards,

**Comment by kcooney** [comment] 2016-10-12 13:49
@htetmyomyint can you provide an example that demonstrates this problem?

**Comment by htetmyomyint** [comment] 2016-10-12 15:55
@kcooney I hope you mean this.

Target class

`public class Target {
	public Object targetMethod() {
		return new Object();
	}
	
	public void throwNull(){
		throw new NullPointerException();
	}	
}`

Test class 
`public class Test {
	
	@Test
	public void testThrowNull() {
		Target target = new Target();
		target.targetMethod();
       //do assert
      // assertion may be failed or success
	}

	@AfterClass
	public static void tearDown() {
		Target target = new Target();
		target.throwNull();
	}

}`

When you run only one test method, Unrooted can be seen. ( if you run as the whole class, Unrooted cannot be seen). 

In my case, I expected to throw exception. But that exception is handled inside target method and is not thrown from target method. But code inside @AfterClass method throws my expected exception. Target method used a library. So, error stacktrace is too long and line where exception happen cannot be displayed.

So, I wrongly understood that exception is thrown from my target method, which is correct behavior, and Unrooted error happens when target method throws exception.

Regards,

**Comment by kcooney** [comment] 2016-10-17 04:17
This sounds like the issue fixed by #1082

@htetmyomyint does the problem happen in 4.13?

**Comment by htetmyomyint** [comment] 2016-10-17 21:08
@kcooney yes, it still happens in 4.13.

**Comment by kcooney** [comment] 2016-10-18 22:39
@htetmyomyint thanks for checking. Since you are the only one that has seen this, could you try stepping through with a debugger to see what is causing the problem? I suspect you would want to set breakpoints in `BlockJUnit4ClassRunner.runChild()` and in `RunAfters.evaluate()`

**Comment by kcooney** [comment] 2017-01-08 20:08
@htetmyomyint I was able to reproduce this and it looks like an Eclipse bug.

Eclipse appears to do the following

1. Create a Request to run `Test`
2. Filter the request with `Request.filterWith(Description)`
3. Use the `Request` returned by step 2 to run the test

In order to run the test method, we of course have to run the `@AfterClass` method. As far as I can tell, JUnit properly notifies the registered `RunListener` instances about the failure. My guess is Eclipse shows this as an unrooted test because it assumes that the root of the test run is the test method, but of course it isn't.

IMHO, Eclipse should show the top-level class in the JUnit UI when you run a single method in the class, so it has somewhere in the UI to show the class-level failures.

**Comment by adrianosimoes** [comment] 2017-01-22 20:09
So, is this a Eclipse bug and not a JUnit bug?

**Comment by kcooney** [comment] 2017-01-22 22:50
@adrianosimoes yes, I believe it is an issue with the Eclipse JUnit integration.

**Comment by adrianosimoes** [comment] 2017-01-22 22:53
Then, should this issue be closed?

**Comment by kcooney** [comment] 2017-01-22 22:55
@adrianosimoes it's still an issue, just not one we believe we can fix on our side.

**Comment by kcooney** [comment] 2017-01-30 05:31
FYI: This sounds similar to https://bugs.eclipse.org/bugs/show_bug.cgi?id=297280 which was marked as fixed. I think the fix was targeted to 3.6 M5. I think I verified the problem in Eclipse 4.6.2

**Comment by marcphilipp** [comment] 2017-02-04 09:57
I'm closing this issue as it was a bug in Eclipse that has been fixed in the meantime.

**Closed by marcphilipp** 2017-02-04 09:57 UTC
Labels: bug, external issue
