### ISSUE TITLE
@Test annotation is not composable, please add @Target ElementType.ANNOTATION_TYPE

### ISSUE THREAD

**Issue by natancox** [junit-team/junit4#1431] opened 2017-03-17 16:39 UTC
I really want to add ElementType.ANNOTATION_TYPE in the @Test annotation because I want to combine a number of annotations into one custom annotation.

```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE})
public @interface Test {...}
```

Currently, a lot of my tests look like which gets a bit boring because it is 3 lines of code for each test.

```
@Test
@DirtiesContext
@Transactional
public void test() {}
```

So I want to be able to combine them in a single annotation like this

```
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@Test
@DirtiesContext
@Transactional
public @interface DirtyTest {
}
```

So I can finally do this

```
@DirtyTest
public void test() {}
```

**Comment by kcooney** [comment] 2017-03-18 00:22
This is a duplicate of #194

**Closed by kcooney** 2017-03-18 00:22 UTC
