### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by rajusah15** [junit-team/junit4#1713] opened 2021-07-28 09:33 UTC
while executing the mvn test, getting below error
Test set: org.junit.rules.TemporaryFolderUsageTest
-------------------------------------------------------------------------------
Tests run: 24, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec <<< FAILURE! - in org.junit.rules.TemporaryFolderUsageTest
newFolderWithGivenFolderThrowsIOExceptionWhenFolderCannotBeCreated(org.junit.rules.TemporaryFolderUsageTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: Expected test to throw (an instance of java.io.IOException and exception with message a string containing "could not create a folder with the path 'level1'")

**Comment by pmcder** [comment] 2021-07-29 21:42
It looks like #1705 was about this issue as well. I haven't been able to reproduce in my branch/environment. There were some follow up questions on #1705 that might provide some more insight here.

**Comment by marcphilipp** [comment] 2021-08-05 08:23
Duplicate of #1705

**Closed by marcphilipp** 2021-08-05 08:23 UTC
