### ISSUE TITLE
ExpectedException fails when assumption fails

### ISSUE THREAD

**Issue by smithkm** [junit-team/junit4#1566] opened 2018-10-23 20:53 UTC
I have tests that `Assume.assumeTrue(false)` under some circumstances to indicate the test is not relevant.  Some of these tests are using an `ExpectedException` rule to check for other exceptions.  Under JUnit 4.11 the test gets ignored as expected, under JUnit 4.12 the rule tries to match the `AssumptionViolatedException` and fails.

Probably related to the fix for #687

**Comment by kcooney** [comment] 2018-10-23 21:55
Thanks for reporting this

If you are using 4.12 I strongly recommend replacing usages of `ExpectedException` with `org.junit.Assert.assertThrows`.

**Comment by smithkm** [comment] 2018-10-24 00:11
It doesn't appear that's in 4.12.  For now I've made it work with some `@Ignore`s but I may try putting in my own `assertThrown` until 4.13

**Comment by kcooney** [comment] 2018-10-24 04:51
Woops, sorry,  `assertThrows` will be added in JUnit 4.13

**Comment by kcooney** [comment] 2018-10-24 05:04
Looking at the threads (particularly #720) it sounds like we changed this behavior in 4.11, realized that the new behavior was a bad idea, and reverted to the 4.10 behavior in 4.12.

@smithkm How does your test behave in JUnit 4.10?

**Comment by kcooney** [comment] 2018-10-24 16:30
@smithkm It looks like we have a test case for exactly this use case:

https://github.com/junit-team/junit4/blob/master/src/test/java/org/junit/rules/ExpectedExceptionTest.java#L279

This results in an `AssumptionFailure` (i.e. the test will be effectively ignored)

If you call `ExpectedException.expect()` before calling `assumeTrue()` or `assumeFalse()` then the test will fail (not be ignored).

**Comment by allanhaywood** [comment] 2021-11-30 06:15
@kcooney @smithkm Is this still an issue?

**Comment by kcooney** [comment] 2021-12-02 11:23
@allanhaywood based on the JUnit self tests, `ExpectedException` works as expected when there is an assumption failure.

Unless someone provides a minimal, complete and verifiable example demonstrating it, I think we should close it as not reproducible

**Comment by marcphilipp** [comment] 2021-12-02 13:27
Optimistically closing. I'd reopen it if someone provides a reproducer.

**Closed by marcphilipp** 2021-12-02 13:27 UTC
